### ISSUE TITLE
No warning when the app couldn't send a word to Firestore

### ISSUE THREAD

**Issue by Kwak04** [Kwak04/KwakVoca#27]
### Firestore에 단어를 전송하지 못했을 때 경고가 표시되지 않음.
경고가 표시되지 않고 완료 버튼을 눌러도 아무런 동작이 없음.

**Comment by Kwak04** [comment]
네트워크에 연결되어 있지 않을 때 경고를 표시해야 함.

**Comment by lio8192** [comment]
### **

> 빨리 고쳐야겠네요!

**

**Comment by Kwak04** [comment]
AddWordsActivity의 종료되는 시점이 버튼을 누르고 바로 다음으로 변경되면서 액티비티가 종료되지 않는 문제가 해결됨: #42
